/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qrdztvspsjvligpgbsrn"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZHp0dnNwc2p2bGlncGdic3JuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMzk3NTgsImV4cCI6MjA2ODgxNTc1OH0.XYeWVu1mhLcVREPny5K-AWJd3q-BVk4QDIGLA5C2jVc"